apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql-app
    tier: database
spec:
  containers:
  - name: mysql
    image: mysql:8.4
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root